### ISSUE TITLE
Crash trying to analyse exported facebookmessage-dump

### ISSUE THREAD

**Issue by Philippwolf** [Smirnoffq/fb-chat-stats#3]
Hey Bro,

first and foremost : awesome work, i appreciate it a lot!
I have very intensively chatted with somebody over the course of the past 6 months (17MB chatlog) and would love to see some more detailed statistics!
Sadly I havent gotten it to work myself yet.

Im running into the following erros : 
Win10 x64 / python 3.6.3

\fb-chat-stats\src\messages>python script.py
Fb messages file: 4
Theme name: valentines
Month language: en
Reading messages...    Traceback (most recent call last):
  File "script.py", line 106, in <module>
    weekD = fbDateToWeekday(date)
  File "script.py", line 20, in fbDateToWeekday
    wholeDate = datetime.date(int(fYear), int(fMonth), int(fDay))
ValueError: invalid literal for int() with base 10: '16,'

And i have a small question :  Will the script be able to parse cyrillic letters?

- Peace from Austria
Philipp

**Comment by Smirnoffq** [comment]
Hello, great to hear that someone want to use my script. Unfortunately I cannot help you without example messages, because I have no possibility to reproduce that error.
For now I have too little time to add cyrillic letters, but I will add it to my to do list, and maybe I will add them during summer break.

Best regards, Bartek

**Comment by Smirnoffq** [comment]
After reviewing given example messages I figured out that in Polish language dates of Facebook messages are in `day month_name year` format, and in English `weekday_name, month_name day, year`. This requires deeper code change, and I will work on it whenever I will have some free time.

**Comment by Philippwolf** [comment]
Fixed with latest pullrequest : https://github.com/Smirnoffq/fb-chat-stats/pull/4
